// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdnzpesvqkfupmhnfopc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkbnpwZXN2cWtmdXBtaG5mb3BjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1NjMzMTIsImV4cCI6MjA1NTEzOTMxMn0.LYzvY2xj7fC-REZrlAQgWcUm5oK_buDR26sAaF6yZaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);